[build]
  publish = "."

[[redirects]]
  from = "/confirmed"
  to = "/confirmed.html"
  status = 200

[[redirects]]
  from = "http://*"
  to = "https://inprose.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.inprose.co.uk/*"
  to = "https://inprose.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
